"""Minimal PDF export using reportlab."""

from io import BytesIO

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas


def _wrap(text: str, width: int = 95) -> list[str]:
    lines = []
    for para in text.split("\n"):
        while len(para) > width:
            cut = para.rfind(" ", 0, width)
            cut = cut if cut > 0 else width
            lines.append(para[:cut])
            para = para[cut:].lstrip()
        lines.append(para)
    return lines


def render_pdf(title: str, subtitle: str, body: str) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=LETTER)
    w, h = LETTER
    y = h - inch
    c.setFont("Times-Bold", 20)
    c.drawString(inch, y, title[:80])
    y -= 0.35 * inch
    c.setFont("Helvetica", 10)
    c.setFillGray(0.4)
    c.drawString(inch, y, subtitle[:110])
    y -= 0.4 * inch
    c.setFillGray(0)
    c.setFont("Helvetica", 10)
    for line in _wrap(body):
        if y < inch:
            c.showPage()
            y = h - inch
            c.setFont("Helvetica", 10)
        c.drawString(inch, y, line)
        y -= 14
    c.setFont("Helvetica", 8)
    c.setFillGray(0.5)
    c.drawString(inch, 0.6 * inch, "Generated by Pendulum")
    c.save()
    return buf.getvalue()
